### ISSUE TITLE
iphone xr  os 13.4.1腾讯视频插件看不到播放按钮和控制栏但可以点  android 正常

### ISSUE THREAD

**Issue by bby0856** [tvfe/txv-miniprogram-plugin#102]
iphone xr  os 13.4.1腾讯视频插件看不到播放按钮和控制栏但可以点击播放和停止就是看不到按钮  android 正常

 "plugins": {
    "tencentvideo": {
      "version": "1.3.13",
      "provider": "wxa75efa648b60994b"
    }
  }

**Comment by reezon** [comment]
我也遇到同样的问题。播放器界面是纯白色的，什么都看不见
