### ISSUE TITLE
如何评定该视频为盗播视频？长视频只播放3分钟

### ISSUE THREAD

**Issue by lindesu** [tvfe/txv-miniprogram-plugin#105]
如题，引用了腾讯视频里的某一个视频，该视频有20分钟，结果小程序里只播放了3分钟。请问是因为盗播引起的吗？如何评定某视频是否为盗播视频？

**Comment by dhkoma** [comment]
一般情况下有版权的长视频，只能在腾讯视频自己小程序完整播放，外部播放3分钟就是被限播了。
