### ISSUE TITLE
做在线教育类视频，可以设置视频要经过权限判断才能播放吗

### ISSUE THREAD

**Issue by hponiang** [tvfe/txv-miniprogram-plugin#110]

**Comment by dhkoma** [comment]
你说的经过权限，是指你们自己的校验权限吗？这个小程序是不支持的

**Comment by woeoio** [comment]
其实就是类似于优酷视频api的私密播放接口，使得视频在腾讯视频平台不能公开播放和搜索到，仅允许在小程序内部播放

**Comment by woeoio** [comment]
很需要这样的功能

**Comment by dhkoma** [comment]
很抱歉，目前腾讯视频仅支持全平台公开的视频播放，并不支持类似的指定平台播放能力，也暂无相关产品和商业计划。
