### ISSUE TITLE
要怎么监听是否有广告或广告播放完毕？

### ISSUE THREAD

**Issue by syou-yu** [tvfe/txv-miniprogram-plugin#112]
bindended => event.detail.isAd 可以知道广告播放结束，但是跳过广告不会触发。目前我是bindtimeupdate => event.detail.currentTime 第一次 === 0 的时候表示广告被跳过了。能不能统一到 bindended => event.detail.isAd 内表示广告跳过或者已播放结束？
还有一个是，有些视频没有广告，我要怎样知道，因为有要求视频播放时长的需求，所以需要排除掉广告的时间，目前有没有什么好的解决方法？

**Comment by kedanielwu** [comment]
bindended在新版本中会在skip后也触发一次（新版本预计在新年前发布）

当前视频是否是广告可以通过bindcontentchange捕获事件，通过e.detail.currentContent.isAd可以判断是否是广告
