### ISSUE TITLE
video标签即用即毁会报错

### ISSUE THREAD

**Issue by luhuimin** [tvfe/txv-miniprogram-plugin#113]
背景：qq小程序中使用txv-video，多个video形成视频列表，可左右滑动。
目的：为了提高性能，对txv-video即用即毁，不在可视区域的用image代替。
结果：报错，找不到player-id为XXX的txv-video。报错会在滑动video列表时出现，绝大部分情况会报错，偶尔不报错。
猜想：查看报错源，是插件的onTvpTimeupdate报错，插件是否在视频滑到不可视区域时做了些其他操作，但与此同时我又销毁了组件，所以两者冲突报错？

有video即用即毁的需求，但又出现以上报错，希望尽快解决。

**Comment by chbro** [comment]
qq小程序中播放器销毁后会触发pause和timeupdate，导致报错，已兼容发布
