### ISSUE TITLE
是否可以保证腾讯视频上的视频仅在特定渠道可以观看

### ISSUE THREAD

**Issue by EniacTNB** [tvfe/txv-miniprogram-plugin#116]
## 关于视频权限
因为需要腾讯视频中上传本地视频，但本身拥有的视频并不想给公众观看，而是仅可以在企业的小程序中才可以观看 是否能够尽快更新这一部分功能 或者加快腾讯视频 商业平台增值服务中的密码托管的更新？

**Comment by woeoio** [comment]
同求

**Comment by EniacTNB** [comment]
两个月前问了客服，客服意思是即将上线 现在也没见到效果 我怀疑现在这个项目还维护不。

发自我的iPhone

**Comment by dhkoma** [comment]
目前腾讯视频仅支持全平台公开的视频播放，并不支持类似的指定平台播放能力，也暂无相关产品和商业计划。
