### ISSUE TITLE
[BUG]申请去广告后，加载界面，多个视频同时播放

### ISSUE THREAD

**Issue by sunxivincent** [tvfe/txv-miniprogram-plugin#129]
一个界面有多个视频，已经付费去掉了广告，iOS， 设置autoplay="{{false}}" 也无效。进入界面后所有视频同时加载播放。

**Comment by Shihongji** [comment]
把autoplay="{{false}}" 这个配置去掉试试
我遇到同样问题，去掉这个设置 OK 了
