### ISSUE TITLE
uniapp使用2.0.0版本加载不出来，没看出有什么报错

### ISSUE THREAD

**Issue by baiNan-git** [tvfe/txv-miniprogram-plugin#136]
![image](https://user-images.githubusercontent.com/49094449/142372882-3718224b-c655-4f4e-a538-51354e6db1e1.png)
![image](https://user-images.githubusercontent.com/49094449/142372920-77881403-6057-4af6-b74f-66eb2e0a7b0e.png)

**Comment by baiNan-git** [comment]
![image](https://user-images.githubusercontent.com/49094449/142372986-53bf780f-0c4b-40be-b530-9ed2b009dc00.png)

**Comment by kedanielwu** [comment]
只是播放器的部分加载不出来么？看日志的话已经起播了，可以看一下是不是有什么样式导致播放器没有被渲染出来？

**Comment by baiNan-git** [comment]
对，播放器的组件没加载出来，跟控制台的警告有关系吗。。

**Comment by baiNan-git** [comment]
找到原因了，我设置组件宽度100%，不支持，用了固定值就可以出来了

**Comment by kedanielwu** [comment]
是指播放器组件上的属性传入width="100%"这样会出现报错么？
