### ISSUE TITLE
2.0 版本 autoplay 设置为 false 无法播放？很多video参数设置也无效了？

### ISSUE THREAD

**Issue by yyfer** [tvfe/txv-miniprogram-plugin#137]
拿2.0版本测试了下，发现 **autoplay: false** 的时候视频直接黑屏，很多之前的参数现在都无效了

1.5.2 版本都可以正常使用

![image](https://user-images.githubusercontent.com/7627194/142605566-0678ee64-49c9-4e59-8e8f-f495d717a042.png)
![image](https://user-images.githubusercontent.com/7627194/142605761-282d64bb-ab17-4803-a95b-4fdbe4af83f4.png)

**Comment by kedanielwu** [comment]
有部分参数还在逐步同步中。
1. autoplay这个已经计划修复，目前的逻辑下autoplay:false时如果要播放，需要手动调用一下player.start()或者player.play(VID)。
2. 控制栏相关的配置还在迁移中，这些参数需要在useNativeUI="{{true}}"时生效，因为是针对微信原生UI的配置。

**Comment by kedanielwu** [comment]
autoplay已在2.0.1版本中调整，效果同video的autoplay属性
loop也已加入，不过在每次重播的过程中会有一个短暂的loading，这个是由于重播需要重新请求新的视频地址。
