### ISSUE TITLE
视频记忆播放

### ISSUE THREAD

**Issue by Eysen-ZZT** [tvfe/txv-miniprogram-plugin#138]
有没有api设置页面进入时跳转到指定播放时长？

**Comment by kedanielwu** [comment]
播放器不会记录历史观看时长，但是可以通过initial-time指定起播的时间点。
也可以通过接口调用player.play(vid, { startTime: xx })

**Comment by Eysen-ZZT** [comment]
> 播放器不会记录历史观看时长，但是可以通过initial-time指定起播的时间点。 也可以通过接口调用player.play(vid, { startTime: xx })

player.play(vid, { startTime: xx })  这种方式设置时间  xx 需要单位吗，我不带单位，直接给数字好像没有效果。
