### ISSUE TITLE
vid切换后播放器异常，黑屏，无法加载内容

### ISSUE THREAD

**Issue by cbjiang** [tvfe/txv-miniprogram-plugin#141]
部分用户反馈有一直黑屏的情况，表现为广告时长未加载出来，导致一直黑屏，点击播放按钮无效。是否能提供广告加载超时的判断，实现自动重载或者跳过广告？

**Comment by cbjiang** [comment]
除了上述问题，有一个新的问题发现。
当autoplay=false，且初始设置的vid视频没有开始播放时，切换新的vid，播放器会黑屏，无法加载广告和视频内容。
![image](https://user-images.githubusercontent.com/20334060/145964237-7bb24eb5-b504-4ec2-be95-36d7da0b2496.png)

**Comment by cbjiang** [comment]
<player-component id="video" vid="{{cVid1}}" autoplay="{{false}}" useNativeUI="{{true}}"></player-component>
<button type="primary" style="margin: 5px;" bindtap="playCVid1">视频1</button>
<button type="primary" style="margin: 5px;" bindtap="playCVid2">视频2</button>


const app = getApp()

Page({
  data: {
    cVid1:'k33012qvncd',
    cVid2:'s3301n1zhcm'
  },
  onLoad() {
    
  },
  playCVid1:function(){
    const txv = this.selectComponent('#video')
    txv.play(this.data.cVid1);
  },
  playCVid2:function(){
    const txv = this.selectComponent('#video')
    txv.play(this.data.cVid2);
  }
})

**Comment by cbjiang** [comment]
请问有什么进展了吗

**Comment by whatberry** [comment]
我也有这个问题，换到1.5.3则没有问题

**Comment by kedanielwu** [comment]
autoplay=false时的表现的问题已经修改了，现在autoplay应该和video原生的autoplay表现一致，可以升级一下版本试试。

**Comment by kedanielwu** [comment]
已定位到问题，目前只会在autoplay=false下出现。已经记录，预计下周2.0.4可以修复。
