### ISSUE TITLE
腾讯视频插件播放视频卡顿

### ISSUE THREAD

**Issue by dunkong** [tvfe/txv-miniprogram-plugin#142]
最近突然收到很多用户反馈播放视频卡顿，经测试不管是版本是在2.0以上还是之前的1.5.X版本都会出现这种情况，且移动、电信、联通的网络都有可能出现，用户所在区域也无特定区域，出现此问题后插件基本无法播放视频，过段时间自动就好了

**Comment by kedanielwu** [comment]
请问是否是ipv6，蜂窝网络的用户？

**Comment by dunkong** [comment]
我自己这边是蜂窝网络 ，用户那边蜂窝和wifi都有出现过



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ke Daniel ***@***.***&gt;; 
发送时间: 2021年12月22日(星期三) 中午1:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tvfe/txv-miniprogram-plugin] 腾讯视频插件播放视频卡顿 (Issue #142)





 
请问是否是ipv6，蜂窝网络的用户？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dunkong** [comment]
> 请问是否是ipv6，蜂窝网络的用户？

前期未排查清楚，后期排查清楚后发现和ipv6有关，也并非只有蜂窝网络会出现，wifi也会出现，腾讯视频官方小程序此问题也能复现（在播放广告的时候）

**Comment by kedanielwu** [comment]
麻烦提供一下你们这边有问题的appid呢

**Comment by dunkong** [comment]
> 麻烦提供一下你们这边有问题的appid呢

wx411035e11b95e917  这个

**Comment by cbjiang** [comment]
![Dingtalk_20211228143602](https://user-images.githubusercontent.com/20334060/147535890-3740b5ac-8470-4451-8502-df2bfa88f4de.jpg)
我这边最近也发现有些用户无法打开视频，不知道是不是和这个问题有关，请问如何在开发环境复现这个问题

**Comment by dunkong** [comment]
> ![Dingtalk_20211228143602](https://user-images.githubusercontent.com/20334060/147535890-3740b5ac-8470-4451-8502-df2bfa88f4de.jpg) 我这边最近也发现有些用户无法打开视频，不知道是不是和这个问题有关，请问如何在开发环境复现这个问题

不出意外应该是同样的问题，复现也很简单，可以先用自己那边的ipv6网络试下，如果自己这边没问题就得让用户协助下，让他帮忙真机调试一下，目前我所知道的是部分地区的ipv6网络下会这样，但是一直修复问题一直没进展，难受

**Comment by cbjiang** [comment]
我这边从反馈看，确实和地区网络有些关系，很多都是离开常用地，然后出现的问题，发现好几个去成都然后出问题的。
![image](https://user-images.githubusercontent.com/20334060/147545365-9b375717-2347-4664-9945-a8425a39ec0e.png)

找到修复方法希望能告知一下，多谢

**Comment by dunkong** [comment]
> 我这边从反馈看，确实和地区网络有些关系，很多都是离开常用地，然后出现的问题，发现好几个去成都然后出问题的。 ![image](https://user-images.githubusercontent.com/20334060/147545365-9b375717-2347-4664-9945-a8425a39ec0e.png)
> 
> 找到修复方法希望能告知一下，多谢

这个修复我们基本上是做不了什么的，看问题应该是腾讯云cdn侧的问题，cdn上ipv6的时候没弄好，能做的只有等待，问题发现到现在都快有一个月了，一直没啥进展

**Comment by kedanielwu** [comment]
抱歉很长时间才处理完。如果是涉及到ipv6用户的，这部分应该已经恢复正常了。

这里是广告在IPV6环境下的CDN调度有问题，被调度到了海外的节点导致内地用户访问不正常。
