### ISSUE TITLE
2.0文档 期望完善

### ISSUE THREAD

**Issue by bitbw** [tvfe/txv-miniprogram-plugin#143]
😅😅 **2.0文档查看起来太麻烦， 没法直接找到自己想要的属性和事件，建议完善!!**
 👉👉[1.0 的文档](https://github.com/tvfe/txv-miniprogram-plugin/blob/master/archieve/readme.md)的文档就很好查找

**Comment by kedanielwu** [comment]
这里目前还是通过typedoc生成的，目前还在寻找一个效果比较好的自动化方案。由于微信的限制，文档只能外链到github来，没办法用vuepress等完全建站。
