### ISSUE TITLE
广告在使用流量时长时间卡顿

### ISSUE THREAD

**Issue by luweihub** [tvfe/txv-miniprogram-plugin#147]
视频播放前的广告在使用流量时大部分机型都会长时间卡顿
wx626025001c1d7339

**Comment by luweihub** [comment]
使用了腾讯视频商业平台免广告试用，没广告时此问题不存在，说明广告部分影响了视频的加载，超长时间卡在广告页，秒数不动，希望加以优化

**Comment by kedanielwu** [comment]
2.0.6版本为广告追加了15秒自动超时，请问用户是在ipv6的环境下吗，可否提供用户所在的地区？

**Comment by luweihub** [comment]
是的，南京，刚刚我找上海的用户测试一下，也是大部分手机卡在视频广告

**Comment by kedanielwu** [comment]
麻烦提供一下具体的小程序名称，appid无法查询到

**Comment by luweihub** [comment]
十角兽合伙人

**Comment by luweihub** [comment]
我已更换了打开视频方式，希望能修复这个问题再以后有需要时能顺利使用
