### ISSUE TITLE
广告播放结束后黑屏，无法继续播放

### ISSUE THREAD

**Issue by jamloveu** [tvfe/txv-miniprogram-plugin#149]
2.0.8版本 autoplay=false 控制play 广告播放结束后，播放器黑屏，播放不了

**Comment by kedanielwu** [comment]
麻烦提供一下appid，代码片段。以及用腾讯视频小程序是否会有相同的情况？

**Comment by idzhiwei** [comment]
就是用的这个仓库的[示例代码](https://github.com/tvfe/txv-miniprogram-plugin/tree/master/archieve)，版本改为2.0.8，autoplay=false

**Comment by kedanielwu** [comment]
这个仓库archive内的文件不一定适用于2.0.8版本。可以直接用readme里的
