### ISSUE TITLE
视频播放结束后，点击播放按钮没反应

### ISSUE THREAD

**Issue by NingCorleone** [tvfe/txv-miniprogram-plugin#150]
视频播放结束后，点击播放按钮没反应（想要重头再播放），也不会触发 play 事件。

请问这是插件的问题。还是需要开发者自己实现这个功能。

![image](https://user-images.githubusercontent.com/53388444/154241078-2a5c2ec8-6899-4d3d-b6a8-0ba7158f5844.png)

**Comment by NingCorleone** [comment]
"player": {
				"version": "2.0.5",
				"provider": "wxa75efa648b60994b"
			}

**Comment by kedanielwu** [comment]
播放完成后如果要重新播的话目前需要调用replay方法。
不过这里的体验的确不太好，我们记一下，播放完成后这里的ui应该展示为重播按钮。

**Comment by NingCorleone** [comment]
弱弱地问一句，现在这个ui 。播放结束后 再点那个播放按钮会触发什么事件呢

**Comment by kedanielwu** [comment]
不会触发任何事件，包括ui的操作实际上也不会有响应

**Comment by kedanielwu** [comment]
2.1版本在停止后，点击播放按钮会重播上一个vid，进度条目前还未适配。
