### ISSUE TITLE
bug：微信小程序中无法是用play（）方法播放视频

### ISSUE THREAD

**Issue by Gentlemenfeng** [tvfe/txv-miniprogram-plugin#151]
**wxml:** 
 <player-component  class="video fullscreen-video" showProgress="{{false}}" controls="{{false}}" id="video-51" autoplay="{{false}}" >
  </player-component>
**js:**
  /**
   * 生命周期函数--监听页面初次渲染完成
   */
  onReady: function () {
    const q = this.selectComponent('#video-51');
    q.play('n0042928ae2')     
  },
**json:**
    "player-component": "plugin://player/video"
**app.json:**
  "plugins": {
    "player": {
      "version": "2.0.4",
      "provider": "wxa75efa648b60994b"
    }
  },

**Comment by kedanielwu** [comment]
请问控制台有输出报错或播放器有出现错误页吗？

**Comment by Gentlemenfeng** [comment]
> 请问控制台有输出报错或播放器有出现错误页吗？

控制台无报错，播放器无报错页面

**Comment by Gentlemenfeng** [comment]
> 请问控制台有输出报错或播放器有出现错误页吗？

请问下，这个问题有复现么
