### ISSUE TITLE
广告是黑屏，只有声音

### ISSUE THREAD

**Issue by iamxjb** [tvfe/txv-miniprogram-plugin#152]
打开腾讯视频最开始的广告是黑屏，只有声音。从2.0.0版本开始都有这个问题。换回1.5.3版本就正常了。

**Comment by kedanielwu** [comment]
请问腾讯视频的小程序有类似情况吗？如果没有的话麻烦提供一下代码片段

**Comment by iamxjb** [comment]
腾讯视频的小程序正常。我的小程序不正常，打开后广告无法正常加载，黑屏，有声音，广告播放完后显示视频，可播放。代码如下：

app.json
 "plugins": {
    "tencentvideo": {
      "version": "2.1.0",
      "provider": "wxa75efa648b60994b"
    }
}


index.wxml

 <txv-video vid="u0858q9zzl9" controls="true" /> 

index.json

"usingComponents": {       
        "txv-video": "plugin://tencentvideo/video"       
    }

**Comment by iamxjb** [comment]
我找到原因是，是因为层级的问题导致的。其实广告记载出来，只是层级的原因导致看到的是黑屏。
