### ISSUE TITLE
视频中间的播放按钮不显示

### ISSUE THREAD

**Issue by 5563** [tvfe/txv-miniprogram-plugin#159]
使用版本` "version": "2.1.0" ` 时候   video 组件中间不显示播放按钮 
![image](https://user-images.githubusercontent.com/57325200/183829631-e0d82bc9-ec9a-4d98-b868-c12872a38347.png)

版本换成` "version": "1.3.18"`时候就会出现中间播放按钮 但是如果不设置poster的时候被强制加了` poster="http://shp.qpic.cn/qqvideo/0/d3351g0vwwa/0"`这个空白图片
![image](https://user-images.githubusercontent.com/57325200/183830064-d753e2f6-2f59-44e0-bcec-3e655c379bd1.png)

**Comment by kedanielwu** [comment]
1.3.18可以设置usePoster=false的属性，目前这个问题我们没办法修复了，封面图的服务下线，旧版本我们无法覆盖更新。

2.1的center-btn的确没有加上，这个我们后续补充
