### ISSUE TITLE
【管理员吐血留言】由于近期申请人数过多，请同时留下你们的申请时间

### ISSUE THREAD

**Issue by zombieyang** [tvfe/txv-miniprogram-plugin#16]
还是将请求留言至[这里](https://github.com/tvfe/txv-miniprogram-plugin/issues/2)

**Comment by zyfAnd** [comment]
微信 zyfJava
看视频学英语
谢谢

**Comment by Mr-Jemp** [comment]
小程序：弹球福利大作战
appid：wx8e39a9055484ad19
开发者微信：Xiaojian1303232158
申请时间：2018/8/30/16:50

@xosuperpig 谢谢

**Comment by Systempm** [comment]
小程序：计算器音乐乐谱
开发者微信：systempm
申请时间：2018年9月6日21:13:56
