### ISSUE TITLE
bindstatechange绑定状态变化事件，视频加载进来就是playing状态

### ISSUE THREAD

**Issue by GloriousFt** [tvfe/txv-miniprogram-plugin#18]
问题前提是，页面有个视频列表，默认加载第一个视频，点击其他视频时组件更换vid属性。

页面初始状态<txv-video>没有vid属性，异步数据请求回调中更新了vid的值，然后发现bindstatechange绑定的事件中，newstate是playing，oldstate是ready，但是视频并没有播放。

之后视频播放点击暂停时，bindstatechange绑定事件不被触发。

有个建议就是能否将原生组件<video>中的bindplay等属性放出来？

**Comment by glj233** [comment]
这个插件，视频加载 直接自动播放？

**Comment by GloriousFt** [comment]
不，加autoplay才会自动播放。
但是我遇到的问题是，视频没有自动播放，但是状态值却变成了playing。后续的再点击播放，状态值没变化。

**Comment by glj233** [comment]
我测试 这个官方的 样例，   视频直接播放， autoplay 参数 失效了

**Comment by smallyaohailu** [comment]
bindstatechange 无效，你们遇到这个问题了吗

**Comment by GloriousFt** [comment]
目前是生效的，但是我这边1.1.3版本里状态变化依然有问题，一进来就是playing状态，但是视频根本没播放。怀疑是不是广告的问题。

**Comment by aliarmo** [comment]
广告和正片是一个周期，暂时未做区分
bindstatechange，在视频资源的加载过程中会抛出loading， ready， playing， end，error这几个事件，回调函数的参数里面有两个属性newState，oldState
loading(视频资源加载中)
ready(资源就绪)
playing(开始播放)
end(播放结束)
error(资源加载失败)
