### ISSUE TITLE
小程序名字和联系方式统一收集楼

### ISSUE THREAD

**Issue by zombieyang** [tvfe/txv-miniprogram-plugin#2]
为了防止后续出问题找不到接入方，需要你们留一下联系方式
```
小程序名字: 
qq/微信:
申请时间:
```

**Comment by youngjuning** [comment]
小程序名字：BestTest
微信：15638226798
qq：1003719811

**Comment by youngjuning** [comment]
小程序名字：私塾国际学府
微信：15638226798
qq：1003719811

**Comment by LinNiuBi** [comment]
小程序名字：家庭科学小实验
qq：313065312

**Comment by km567** [comment]
小程序名称：太心动音乐
微信：km567lhw

**Comment by zhangtaii** [comment]
小程序名称：点开小视频
微信：zhangtaii_wx

**Comment by luckymuye** [comment]
小程序名字：智慧校园小精灵 
qq：493353079
@xosuperpig

**Comment by 1563172697** [comment]
小程序名称：偏执分享
qq：1563172697

**Comment by luckymuye** [comment]
小程序名字：zx每日听
qq：493353079
@xosuperpig

**Comment by willdx** [comment]
小程序名字：imdancer
微信：dx1426409836
qq：1426409836
@xosuperpig  Thanks!

**Comment by redmaple21** [comment]
小程序名字：Felix修行之地
微信：RockRule
只是自己用来学习的小demo，希望能给通过

**Comment by mzmz1016** [comment]
小程序名字：iDVENTURE
QQ：3443323283
学习用，望通过，THX！

**Comment by 1115332213** [comment]
名称：维多利亚的秀
wx: yangshuolll

**Comment by suonian** [comment]
小程序名字：小桃子之家
QQ：2351735729
@xosuperpig

**Comment by yzqiang** [comment]
小程序名字：北京TATA
微信：qiangdadadada
qq：562729585

**Comment by 923145852** [comment]
小程序名字：i抽奖
微信：CMH923145852
qq：923145852

**Comment by array007** [comment]
小程序名字：狐狸快看
微信：fire_in-the-hole
@xosuperpig

**Comment by 424626154** [comment]
小程序名字:创造与魔法盒子
微信:sbb001
QQ:424626154
@xosuperpig

**Comment by shannan1989** [comment]
小程序名字:排球迷
QQ:951845510

申请使用插件@xosuperpig

**Comment by 424626154** [comment]
小程序名字:方舟手游盒子
微信:sbb001
QQ:424626154
@xosuperpig

**Comment by wendal** [comment]
小程序名字: 山海日料
微信: wendal
QQ: 389627265

**Comment by 1115332213** [comment]
名称：随手听英语
wx: yangshuolll

**Comment by hardog** [comment]
小程序名称： 说练英语
QQ：2063714602
微信：ncu_zp

**Comment by 1115332213** [comment]
名称：随手练英语
wx: yangshuolll

**Comment by realperson** [comment]
小程序名字: 城市圈平台
qq:1750698766

**Comment by shuaimoumou** [comment]
小程序名字：暂时没名字
微信：564544662
qq：564544662
@xosuperpig

**Comment by cocobele** [comment]
小程序名字：点开就看
微信：cocobele
qq：124155148
@xosuperpig

**Comment by 424626154** [comment]
小程序名字:武林外传盒子
微信:sbb001
QQ:424626154
@xosuperpig

**Comment by duheng** [comment]
小程序名字：乐学营特惠亲子演出活动旅行酒店
 qq： 252072933 ；
@xosuperpig    谢谢

**Comment by wangyuanjie** [comment]
小程序名称：微喜
微信yb5618
qq：814445799
@xosuperpig

**Comment by vikingsailor** [comment]
@xosuperpig  

小程序名字: 入园通
微信:vikingsailor

**Comment by devilfan** [comment]
小程序名字:  钱儿频道会员
qq/微信:  258640006
申请时间: 2018-6-16 13:48

小程序名字:  钱儿频道
qq/微信:  258640006
申请时间: 2018-6-19 12:58

**Comment by trtst** [comment]
小程序名字:  摩尔投研
 @qq: 569615439
申请时间:  2018-6-20 15:55
@xosuperpig

**Comment by vikingsailor** [comment]
小程序名字: 入园通
微信:vikingsailor
申请时间2018-6-23 16:04
@xosuperpig

**Comment by singlepa** [comment]
小程序名字：芝麻快瘦
qq ： 573016703
申请时间：2018-6-27 11:47

**Comment by radrupt** [comment]
小程序：BigNoNo儿童礼物DIY
我的微信：wangd933
申请时间2018-7-1 11:21
@xosuperpig
谢谢!

**Comment by baobaoblue** [comment]
小程序：张窝便民
我的微信：zhangtaoeasy
申请时间2018-7-22 11:21
@xosuperpig 
谢谢!

**Comment by stevenli092843** [comment]
小程序： UPro设计学院
appID：	wx6aa20b18e321eb6e
申请时间： 2018-8-12 19:17

开发者微信： lixiaotong4133
开发者QQ： 276125681

@xosuperpig 
谢谢！

**Comment by wcy92929292** [comment]
小程序：最新在线影视
appID：wxf3175ed0455d749d
申请时间：2018-08-13 14:00
开发者微信：wuyangyang2013
开发者qq：1035773609

@xosuperpig 
谢谢啦！

**Comment by jingzhilife** [comment]
小程序名字: mpvueJing
微信: jing1005548924
申请时间: 2018.08.14   11:48

谢谢

**Comment by pimktine** [comment]
小程序：学习好极了
appid：wx867e285a0b8cfa27
开发者微信：18019322055
开发者qq：365670648
申请时间：2018/8/26 19：36

**Comment by Mr-Jemp** [comment]
小程序：弹球福利大作战
开发者微信：Xiaojian1303232158
开发者QQ：1303232158
申请时间：2018/8/30/16:50

**Comment by Mr-Jemp** [comment]
小程序：弹球福利大作战
appid：wx8e39a9055484ad19
开发者微信：Xiaojian1303232158
申请时间：2018/8/30/16:50

@xosuperpig 谢谢~

**Comment by liejiayong** [comment]
小程序： 贪玩游戏
QQ/微信： 809206619
申请时间： 2018-9-03

@xosuperpig 谢谢
