### ISSUE TITLE
几个问题咨询一下

### ISSUE THREAD

**Issue by yautah** [tvfe/txv-miniprogram-plugin#21]
1. 竖屏录制的视屏，在全屏播放的时候是横屏全屏，能否是竖屏全屏呢？否则观看体验很不好啊，就中间那一小溜。原生的video组件是提供播放方向的参数的。。。
2. 如何定制播放区域的样式？比如宽\高？直接设置style貌似无效

**Comment by guodong000** [comment]
+1 如何定制播放区域宽高？经过测试，对txv-video设置宽高之后，其内部的mod_player并不会跟随设定的宽高

**Comment by aliarmo** [comment]
第一点已经支持，传direction
第二点也支持了，传width，height
