### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by baobaoblue** [tvfe/txv-miniprogram-plugin#22]
我看小程序不是有video控件嘛，我看这个插件的功能是一样的，为啥还需要这个插件，有什么不同的应用场景嘛？

**Comment by switer** [comment]
原生的不能播放腾讯视频的源

**Comment by aliarmo** [comment]
1、原生video组件需要视频地址，这样你需要有服务器来存储这个视频，使用插件可以做到你上传视频，然后得到一个vid，传一个vid给我们的插件就好，简单
2、简化video相关操作
3、支持全部只播一个视频，滑出视野自动停播
