### ISSUE TITLE
报错：[non-writable] modification of global variable "App" is not allowed when using plugins at app.json.

### ISSUE THREAD

**Issue by vtnil** [tvfe/txv-miniprogram-plugin#24]
基础库 2.0.9 以上报错：
[non-writable] modification of global variable "App" is not allowed when using plugins at app.json.
[non-writable] modification of global variable "Page" is not allowed when using plugins at app.json.

**Comment by switer** [comment]
插件没有任何关于App/Page的操作，请确认下开发工具版本问题

**Comment by vtnil** [comment]
开发工具版本  1.02.1808080

**Comment by aliarmo** [comment]
问题解决了吗

**Comment by vtnil** [comment]
> 问题解决了吗

解决了，是阿拉丁插件导致的，感谢~

**Comment by geekwill** [comment]
@vtnil 请教下，怎么解决的，如果处理阿拉丁啊。

**Comment by vtnil** [comment]
> @vtnil 请教下，怎么解决的，如果处理阿拉丁啊。

看下阿拉丁集成文档，里面有一种使用插件的集成方式。
