### ISSUE TITLE
视频播放插件，在WXML中解析不出来

### ISSUE THREAD

**Issue by best-fan** [tvfe/txv-miniprogram-plugin#26]
<txv-video vid="e0354z3cqjp" playerid="txv1" autoplay="{{true}}"></txv-video>
![image](https://user-images.githubusercontent.com/18264568/44012592-c8e3353e-9ef2-11e8-8e0f-30b1880bb8bd.png)
求解答

**Comment by aliarmo** [comment]
vid呢，playerid呢，有视频的vid才能找到这个视频哇
vid可以通过在腾讯视频上传得到http://v.qq.com/u/upload.html
