### ISSUE TITLE
bindstatechange 绑定无效，真闹心啊

### ISSUE THREAD

**Issue by smallyaohailu** [tvfe/txv-miniprogram-plugin#31]
<txv-video   bindstatechange="bindplay"  bindplay="bindplay" playerid="{{listName.id}}" data-id="{{listName.id}}"  vid="{{listName.extSencond}}" autoplay="{{false}}"></txv-video>

 bindplay: function (e) {
    console.log("我播放了，我的id是"+JSON.stringify(e));
  }

**Comment by smallyaohailu** [comment]
` bindplay: function (e) {
    console.log("我播放了，我的id是"+JSON.stringify(e));
  }`

**Comment by smallyaohailu** [comment]
`        <txv-video   bindstatechange="bindplay"  bindplay="bindplay" playerid="{{listName.id}}" data-id="{{listName.id}}"  vid="{{listName.extSencond}}" autoplay="{{false}}"></txv-video>`

**Comment by smallyaohailu** [comment]
<txv-video   bindstatechange="bindplay"  bindplay="bindplay" playerid="{{listName.id}}" data-id="{{listName.id}}"  vid="{{listName.extSencond}}" autoplay="{{false}}"></txv-video>

**Comment by smallyaohailu** [comment]
"newstate":"playing","oldstate":"ready"   加载的时候，他就已经是从ready 进入了 playing

**Comment by aliarmo** [comment]
bindstatechange，在视频资源的加载过程中会抛出**loading， ready， playing， end，error**这几个事件，回调函数有两个参数newState，oldState
loading(视频资源加载中)
ready(资源就绪)
playing(开始播放)
end(播放结束)
error(资源加载失败)

**Comment by smallyaohailu** [comment]
thank you ,  Problem has been resolved

**Comment by aliarmo** [comment]
bindstatechange，在视频资源的加载过程中会抛出loading， ready， playing， end，error这几个事件，回调函数的参数里面有两个属性newState，oldState
loading(视频资源加载中)
ready(资源就绪)
playing(开始播放)
end(播放结束)
error(资源加载失败)

**Comment by smallyaohailu** [comment]
> bindstatechange，在视频资源的加载过程中会抛出loading， ready， playing， end，error这几个事件，回调函数的参数里面有两个属性newState，oldState
> loading(视频资源加载中)
> ready(资源就绪)
> playing(开始播放)
> end(播放结束)
> error(资源加载失败)

thank you , Problem has been resolved

**Comment by aliarmo** [comment]
好滴，解决方案说下，供后面的人参考

**Comment by smallyaohailu** [comment]
> 好滴，解决方案说下，供后面的人参考

太久了，都忘了。。。

我后来发现 bindstatechange   其实是管用的。。。

我是自己利用另一个事件，变相的实现了。。。

那个事件，我记得是实时性很强。。。 我做了一个算法，视频播放超过多少秒 算 视频被播放了。。。
