### ISSUE TITLE
有个问题

### ISSUE THREAD

**Issue by lsyuan1984** [tvfe/txv-miniprogram-plugin#36]
去不掉广告 没关系 我的目标是 播放当前视频 当视频划出可视界面时我就暂停播放，这个能实现，但是在播放广告时 当视频划出可视界面时我就暂停播放，那就不能再继续点击播放了 头疼。。。

**Comment by aliarmo** [comment]
目前最新版本已经支持滑出视野暂停播放了，广告也加了播放和暂停功能
