### ISSUE TITLE
个人主体不支持视频插件？

### ISSUE THREAD

**Issue by zyfAnd** [tvfe/txv-miniprogram-plugin#41]
之前的我的小程序用这个视频插件还审核通过了，现在更新版本的时候再审核就给出了如下的未通过原因
你的小程序"看视频学英语"代码发布审核未通过，原因如下：
1:小程序内容不符合规则:
(1):你好，个人主体小程序暂不支持使用文娱-视频插件，请修改后再提交审核。
如有疑问，请查看详情与反馈。

**Comment by aliarmo** [comment]
目前是个人不能使用插件
