### ISSUE TITLE
升级到1.2.2 报错 提示找不到插件

### ISSUE THREAD

**Issue by museL** [tvfe/txv-miniprogram-plugin#50]
升级到1.2.2 报错 提示找不到插件
Component is not found in path "plugin://wxa75efa648b60994b/live" (using by "pages/video/video_list/video_list")
配置如下
{
     "disableScroll": true,
     "navigationBarTextStyle":"white",
     "usingComponents": {
          "txv-live": "plugin://tencentvideo/live"
     }
}

**Comment by switer** [comment]
#49
