### ISSUE TITLE
调试基础库2.3.1出现[non-writable] modification of global variable "wx.version" is not allowed when using plugins at app.json.

### ISSUE THREAD

**Issue by fanties** [tvfe/txv-miniprogram-plugin#51]
在真机和调试基础库2.3.1出现
[non-writable] modification of global variable "wx.version" is not allowed when using plugins at app.json.
只引入了一个插件
"plugins": {
    "tencentvideo": {
      "version": "1.2.2",
      "provider": "wxa75efa648b60994b"
    }
  }

**Comment by switer** [comment]
插件没有修改wx.version逻辑，我猜这是微信开发者工具、基础库的bug

**Comment by kiyoometal** [comment]
把版本库调低一点就不报错了。

**Comment by JohnChan1017** [comment]
【详情】-> 【调试基础库】调到最新版即可

**Comment by douzhiwei** [comment]
1.升级`wepy-async-function`到最新版本,当前最新版本是1.4.7
2.调试基础库调到最新
