### ISSUE TITLE
视频可以正常播放，连续报[找不到playerid为p***的txv-video组件]错误

### ISSUE THREAD

**Issue by james9527** [tvfe/txv-miniprogram-plugin#52]
thirdScriptError
找不到playerid为p05111r3gvi的txv-video组件
PS：我设置了自动播放 autoplay="{{true}}"，打开视频详情页后，视频可以正常自动播放
<img width="956" alt="wechatimg362" src="https://user-images.githubusercontent.com/9150804/47605608-4fb52f80-da3b-11e8-9c41-299721b7dfea.png">

**Comment by switer** [comment]
贴下你的使用代码，包括WXML

**Comment by yannbaba** [comment]
一样的错误，其他人没有遇到吗
