### ISSUE TITLE
腾讯视频插件的优先级z-index

### ISSUE THREAD

**Issue by flexmodule** [tvfe/txv-miniprogram-plugin#53]
是优先级最高吗，改变了，好像没用，在开发者工具中有用，真机调试还是没用

**Comment by flexmodule** [comment]
txv这个插件并不是原生组件啊

**Comment by switer** [comment]
里面的视频播放组件是原生的

**Comment by flexmodule** [comment]
我猜里面的组件是原生的。。。。。。。。。。。。果然，，，，，小程序就是跳出了一个坑，又进入了另一个坑

**Comment by switer** [comment]
小程序在做video组件的同层渲染，表现可以跟普通的元素一样，再等等吧

**Comment by js-shunchenghunter** [comment]
当前在某些机型上如ios12，嵌入组件内的cover-view还是由于层级低的原因被video覆盖
