### ISSUE TITLE
为什么有的视频一直在播广告，是插件的bug吗？视频在浏览器正常播放

### ISSUE THREAD

**Issue by flexmodule** [tvfe/txv-miniprogram-plugin#54]
是插件bug还是网速问题

**Comment by switer** [comment]
有对应的视频VID吗？

**Comment by fightingljm** [comment]
vid  :    o07788zwjbg
@switer

**Comment by fightingljm** [comment]
> 播放广告之后就停止了，点击播放还是广告

解决了吗

**Comment by aliarmo** [comment]
我这里拿这个vid没有复现，<tx-video vid="o07788zwjbg" playerid="txv1"></tx-video> 试试直接这样使用呢，如还有问题，请加群807339057

**Comment by zsuswy** [comment]
同样有这个问题，一直播放广告。

**Comment by jinchaoxiang** [comment]
同样有这个问题，一直播放广告。

**Comment by jinchaoxiang** [comment]
同样是这个问题

**Comment by jinchaoxiang** [comment]
如果是动态赋值vid值 需要加wx-if=“{{vid}}” 不然组件生效的时候会找不到vid

**Comment by jinchaoxiang** [comment]
@flexmodule
