### ISSUE TITLE
小程序引入插件失败

### ISSUE THREAD

**Issue by scau009** [tvfe/txv-miniprogram-plugin#57]
app.js的配置如下：
![image](https://user-images.githubusercontent.com/18747266/49328921-0c5a5d80-f5b3-11e8-9dc1-91365089421d.png)
页面配置和引入：
![image](https://user-images.githubusercontent.com/18747266/49328926-1d0ad380-f5b3-11e8-9457-5ab6d02e235c.png)
开发者工具报错如下
![image](https://user-images.githubusercontent.com/18747266/49328913-f3ea4300-f5b2-11e8-87f6-b956b09a2875.png)
劳烦解答

**Comment by switer** [comment]
微信基础库版本多少？

**Comment by scau009** [comment]
> 微信基础库版本多少？

![image](https://user-images.githubusercontent.com/18747266/49329391-25660d00-f5b9-11e8-83fb-0301f4b703d6.png)
2.4.1

**Comment by aliarmo** [comment]
app.json里面配置的插件名称叫tencentvideo，而不是myPlugin

**Comment by aliarmo** [comment]
试试将app.json里面配置的插件名称改叫tencentvideo，而不是myPlugin

**Comment by scau009** [comment]
> 试试将app.json里面配置的插件名称改叫tencentvideo，而不是myPlugin

不行哦

**Comment by walkedSnail** [comment]
> > 试试将app.json里面配置的插件名称改叫tencentvideo，而不是myPlugin
> 
> 不行哦

usingComponents: {
                'txv-video': 'plugin://tencentvideo/video'
            }
将txv-video改成video就可以

**Comment by fffx** [comment]
@walkedSnail   这里多了空格
![image](https://user-images.githubusercontent.com/11586335/50374834-3b527500-062f-11e9-99fd-dc7e0ab79bc2.png)
