### ISSUE TITLE
video 标签内只能嵌套 <cover-view /> 和 <cover-image />。

### ISSUE THREAD

**Issue by maoriaty** [tvfe/txv-miniprogram-plugin#58]
报错：video 标签内只能嵌套 <cover-view /> 和 <cover-image />。

> <txv-videois="plugin-private://wxa75efa648b60994b/component/video/video">
#shadow-root
<viewclass="mod_player"style="width: ; height: ">
<videobindended="__onTvpEnded"binderror="__onTvpError"bindfullscreenchange="__onTvpFullScreenChange"bindpause="__onTvpPause"bindplay="__onTvpPlay"bindtimeupdate="__onTvpTimeupdate"class="player_video"controls=""danmu-list="[]"initial-time="0"object-fit="contain"poster="http://shp.qpic.cn/qqvideo/0/t0801tv3w72/0"src="http://183.60.23.22/...rom=&fmt=shd&level=0"id="1">...</video>
<viewbindtap="tapRetry"class="player_error_layer hidden"> </view>
<imagehidden=""src="http://dp3.qq.com/stdlog/?bid=weixin&step=2&merged=1&errorcode=100&trycount=0&openid=_f65766aaa5c22321efd1b024dcd&t=0&url=&vid=t0801tv3w72&coverid=&pf=H5&vptag=&pid=&chid=41&tpid=22&reportTime=1543998436121"></image>
</view>
</txv-video>

**Comment by aliarmo** [comment]
以前video是原生组件，内部只能嵌套指定标签，现在可以嵌套view这些常规标签了

![image](https://user-images.githubusercontent.com/40756424/54276225-c193ad00-45c7-11e9-9b9b-d84a5e33c9b0.png)
