### ISSUE TITLE
更新插件申请通过

### ISSUE THREAD

**Issue by CooLoongWu** [tvfe/txv-miniprogram-plugin#64]
小程序名称：轮滑平花进阶教学
更新到最新版本了，麻烦审核通过一下，谢谢。

**Comment by CooLoongWu** [comment]
申请通过下，麻烦给个回复，现在使用的旧版视频插件无法正常播放了

**Comment by aliarmo** [comment]
这里不能进行审核

**Comment by CooLoongWu** [comment]
自动回复：     邮箱已经接收到您的邮件！     我尊敬的主人阅览后会即刻回复您的！                                               拜拜！
