### ISSUE TITLE
请教下这种视频加载内容重叠的情况怎么处理啊

### ISSUE THREAD

**Issue by HONGDUAN** [tvfe/txv-miniprogram-plugin#66]
![image](https://user-images.githubusercontent.com/22188168/53930682-2e411000-40cd-11e9-8747-eb0d2207d323.png)

上下滑动会出现这个问题  安卓有 ios没有  加载完成就正常 我用的一个txv-video组件 滑动的时候替换掉原来的vid  请教下各位大佬

**Comment by aliarmo** [comment]
用户点击图片播放，可以计算这个图片位置，然后把txv-video绝对定位过来
