### ISSUE TITLE
能否在未开始播放时隐藏右上角的文字“5秒后可跳过” ？

### ISSUE THREAD

**Issue by qwqoffice** [tvfe/txv-miniprogram-plugin#67]
这个文字在点击开始播放广告时再显示也不迟，或者可以通过slot来覆盖？
而且中间的15：00，是广告的时长，正确应该是视频的时长才对吧？
![image](https://user-images.githubusercontent.com/18651085/54470261-a3a09500-47df-11e9-9146-737b71c480f7.png)

**Comment by qwqoffice** [comment]
而且这个插件 放在swiper中时会有问题，见下列视频
[![](https://img.youtube.com/vi/jtsvFiDKhmk/0.jpg)](https://www.youtube.com/watch?v=jtsvFiDKhmk)

小程序中video组件已实现同层渲染，按理应该不必再使用cover-view在video上显示内容，使用普通的view即可，view经过测试并不会造成以上的飘动问题

出现问题的小程序码如下：
![image](https://user-images.githubusercontent.com/18651085/54907393-5da2aa00-4f20-11e9-9428-56d137a78243.png)

**Comment by funtask** [comment]
请问这个5秒广告怎么解决，目前层级最高

**Comment by funtask** [comment]
> 这个文字在点击开始播放广告时再显示也不迟，或者可以通过slot来覆盖？
> 而且中间的15：00，是广告的时长，正确应该是视频的时长才对吧？
> ![image](https://user-images.githubusercontent.com/18651085/54470261-a3a09500-47df-11e9-9146-737b71c480f7.png)

看了你们的例子，没有这个五秒广告？

**Comment by qwqoffice** [comment]
> > 这个文字在点击开始播放广告时再显示也不迟，或者可以通过slot来覆盖？
> > 而且中间的15：00，是广告的时长，正确应该是视频的时长才对吧？
> > ![image](https://user-images.githubusercontent.com/18651085/54470261-a3a09500-47df-11e9-9146-737b71c480f7.png)
> 
> 看了你们的例子，没有这个五秒广告？

我使用了一个自定义view来充当cover 然后强制隐藏了5秒广告 等到用户点击播放时才显示回来
```
.plugin-private-wxa75efa648b60994b-component-video-video-3--mod_player .plugin-private-wxa75efa648b60994b-component-video-video-3--player_video .plugin-private-wxa75efa648b60994b-component-video-video-3--mod_skipad {
    display: none;
}
```

**Comment by aliarmo** [comment]
1.3.3版本插件会使用view替换cover-view

**Comment by chatterzhao** [comment]
我是菜鸟，能否帮忙提供一下完整代码，比如什么代码写哪里，能实现播放后再显示广告计时

**Comment by MakerGYT** [comment]
> > > 这个文字在点击开始播放广告时再显示也不迟，或者可以通过slot来覆盖？
> > > 而且中间的15：00，是广告的时长，正确应该是视频的时长才对吧？
> > > ![image](https://user-images.githubusercontent.com/18651085/54470261-a3a09500-47df-11e9-9146-737b71c480f7.png)
> > 
> > 
> > 看了你们的例子，没有这个五秒广告？
> 
> 我使用了一个自定义view来充当cover 然后强制隐藏了5秒广告 等到用户点击播放时才显示回来
> 
> ```
> .plugin-private-wxa75efa648b60994b-component-video-video-3--mod_player .plugin-private-wxa75efa648b60994b-component-video-video-3--player_video .plugin-private-wxa75efa648b60994b-component-video-video-3--mod_skipad {
>     display: none;
> }
> ```

自定义组件内部样式可以定义？
