### ISSUE TITLE
【视频播放支持付费去广告啦】，请看(http://v.qq.com/open)

### ISSUE THREAD

**Issue by aliarmo** [tvfe/txv-miniprogram-plugin#69]
使用插件播放视频支持付费去广告啦，详情请看http://v.qq.com/open
付费去广告过程中有问题，随时可以反馈

**Comment by tonnychina** [comment]
有没有办法不通过腾讯视频客户端上传视频，并拿到vid？

**Comment by aliarmo** [comment]
> 有没有办法不通过腾讯视频客户端上传视频，并拿到vid？

看readme，网页上也可以上传，https://v.qq.com/u/upload.html
