### ISSUE TITLE
关于腾讯云的视频服务的点播功能的问题

### ISSUE THREAD

**Issue by MalavitaC** [tvfe/txv-miniprogram-plugin#7]
你好，我现在在腾讯云的视频服务的点播中上传了一个视频
![1](https://user-images.githubusercontent.com/38742840/41214796-b709491a-6d7f-11e8-97ba-87b834bbf0d8.png)
请问这个插件支持播放点播中上传的插件吗？？？

**Comment by 923145852** [comment]
![2](https://user-images.githubusercontent.com/38742840/41215288-3b0d7f36-6d82-11e8-9f4b-1e1b94e291a9.png)
小程序插件详情中，这里说的支持点播和直播是指腾讯云的视频服务吗？

**Comment by Wuwei9536** [comment]
我试了下，腾讯云点播的视频好像不支持，有官方的回复一下吗
