### ISSUE TITLE
播放出错(P.0) MEDIA_ERR_NETWORK

### ISSUE THREAD

**Issue by rachelrrrr** [tvfe/txv-miniprogram-plugin#70]
视频在真机无法正常播放，提示 播放出错(P.0)，但在开发者工具里可以正常播放

binderror捕获到errMsg为MEDIA_ERR_NETWORK，想请教一下该问题是由什么原因导致的？网络环境并没有问题，以及如何解决。谢谢！

![image](https://user-images.githubusercontent.com/17424977/58845523-24b84b80-86ae-11e9-9593-581cc539f67c.png)

**Comment by chebec** [comment]
+1 don't know why?

**Comment by aliarmo** [comment]
有可能是播放地址有问题，vid发一下

**Comment by WAWZ** [comment]
请问解决问题了吗 同遇到此问题
