### ISSUE TITLE
关于视频的广告

### ISSUE THREAD

**Issue by funtask** [tvfe/txv-miniprogram-plugin#72]
1.视频设置poster，但是设置好的海报会显示1到2秒，然后被广告的海报覆盖掉
2.视频上方5秒广告样式显示不全

已经使用最新版本的1.3.5版本，手机版本iPhone7，红米k20

**Comment by funtask** [comment]
[
![video](https://user-images.githubusercontent.com/29862800/59909330-0be7be00-9442-11e9-96a9-d53975c04ad7.jpg)
](url)

**Comment by aliarmo** [comment]
找测试同学帮忙验证了下，没有复现，可加我QQ我找你具体定位下，724183433

**Comment by aliarmo** [comment]
是设置了全局的view的box-sizing为border-box了吧，在引用这个插件的组件中设置view的box-sizing为border-box就好
