### ISSUE TITLE
视频广告右上的『5秒后可跳过』在页面滚动的时候不是随视频一起滚动

### ISSUE THREAD

**Issue by phpcxy** [tvfe/txv-miniprogram-plugin#73]
![](http://ww3.sinaimg.cn/large/006tNc79gy1g4gw4o7il3g30a00hs1ky.gif)

如图

**Comment by phpcxy** [comment]
gif 链接  http://ww3.sinaimg.cn/large/006tNc79gy1g4gw4o7il3g30a00hs1ky.gif

**Comment by aliarmo** [comment]
升级插件版本，应该不会有这个问题
