### ISSUE TITLE
设置loop属性后，循环到第二次就会出现loading，无法继续播放

### ISSUE THREAD

**Issue by bingxueling** [tvfe/txv-miniprogram-plugin#75]
需要视频可以一直循环播放，直到用户自己暂停，但是设置**loop="{{ture}}"**后，每当播放到第二次，就无法继续播放了，滑动进度条跳过此位置可以继续播放，但是点击播放按钮会不断进行loading，小程序本身的video组件没有此bug，希望官方尽快解决下吧。

**Comment by bingxueling** [comment]
这几天发现，此问题在10s内的视频出现较频繁。

**Comment by aliarmo** [comment]
给下出现这个问题的vid和机型，我复现下
