### ISSUE TITLE
插件是否可以获取所播放视频的全网播放量和评论的数据？

### ISSUE THREAD

**Issue by hkfoxok** [tvfe/txv-miniprogram-plugin#81]
如题

**Comment by aliarmo** [comment]
目前暂时不支持，评论可能不行，但是播放量是可以的

**Comment by hkfoxok** [comment]
有具体的获取播放量的API的文件么？能否给我一个链接？还有就是评论是否有开放的计划

发自我的iPhone

在 2019年11月19日，20:39，汪汪 <notifications@github.com> 写道：

﻿

目前暂时不支持，评论可能不行，但是播放量是可以的

**Comment by chatterzhao** [comment]
播放量怎么获取？
