### ISSUE TITLE
视频加载慢，播放卡顿

### ISSUE THREAD

**Issue by SimonTal** [tvfe/txv-miniprogram-plugin#84]
背景：同一个视频，在同样的网络环境中，分别在手机浏览器和微信小程序中播放

描述：在手机浏览器中加载会更快，而在微信小程序中播放，会明显的察觉到加载更慢，广告播放也很卡顿

请问这是因为腾讯视频针对不同渠道服务器不同 还是 小程序插件有什么问题 造成的？

**Comment by aliarmo** [comment]
vid和小程序appid发一下，我查下

**Comment by SimonTal** [comment]
vid: z3022k341ux、s3022ilfrcd、i30236eztjv
appid: wx60a24b3380eb2d33

这边发现小程序上视频都有些卡顿，不限于上面那些 vid。

**Comment by SimonTal** [comment]
@aliarmo 你好请问可以排查下么？

**Comment by aliarmo** [comment]
有两个可能原因：
1、广告播放都卡顿的话，是不是网络问题？看看在4g网络播放情况怎么样
2、页面同时渲染了多个视频播放器？
