### ISSUE TITLE
号外号外，腾讯视频插件可以在QQ小程序上使用啦

### ISSUE THREAD

**Issue by aliarmo** [tvfe/txv-miniprogram-plugin#86]
按文档描述方式接入即可

**Comment by tanchendong1992** [comment]
wepy框架开发的 QQ 小程序如何接入腾讯视频插件.

**Comment by tanchendong1992** [comment]
按照文档方法接入后,报错:  Component is not found in path "plugin://tencentvideo/video" (using by "sub_find/pages/video_play");onAppRoute
Error: Component is not found in path "plugin://tencentvideo/video" (using by "sub_find/pages/video_play")

**Comment by tanchendong1992** [comment]
代码如下
app.js

"plugins": { 
"tencentvideo": { "version": "1.0.0", "provider": "1109840991" 
} } 
使用界面代码如下<template>
   <view>
	<txv-video vid="c3013df4peo"
                   playerid="tencentvideo"
                   autoplay="{{true}}"
        ></txv-video>
    </view>
</template>:
配置:
config = {
    navigationBarTitleText: ' ',
    navigationStyle: 'custom',
    navigationBarBackgroundColor: '#F5F5F8',
    backgroundColorTop: '#F5F5F8',
    backgroundColor: '#F5F5F8',
    navigationBarTextStyle: 'white',
    usingComponents: {
        'txv-video': 'plugin://tencentvideo/video'
    }
}

**Comment by tanchendong1992** [comment]
代码如下
app.js

"plugins": { 
"tencentvideo": { "version": "1.0.0", "provider": "1109840991" 
} } 
使用界面代码如下
<template>
    <view>
	<txv-video vid="c3013df4peo"
                   playerid="tencentvideo"
                   autoplay="{{true}}"
        ></txv-video>
    </view>
</template>

配置:
config = {
    navigationBarTitleText: ' ',
    navigationStyle: 'custom',
    navigationBarBackgroundColor: '#F5F5F8',
    backgroundColorTop: '#F5F5F8',
    backgroundColor: '#F5F5F8',
    navigationBarTextStyle: 'white',
    usingComponents: {
        'txv-video': 'plugin://tencentvideo/video'
    }
}

**Comment by aliarmo** [comment]
> 按照文档方法接入后,报错: Component is not found in path "plugin://tencentvideo/video" (using by "sub_find/pages/video_play");onAppRoute
> Error: Component is not found in path "plugin://tencentvideo/video" (using by "sub_find/pages/video_play")

用QQ小程序的beat版本试试，https://q.qq.com/wiki/tools/devtool
