### ISSUE TITLE
自定义组件

### ISSUE THREAD

**Issue by sunddytwo** [tvfe/txv-miniprogram-plugin#87]
咱们的视频播放插件，是否可以放在自己封装的自定义组件中使用？比如我自定义一个my-component，然后在我的页面中使用my-component。我发现这样使用 视频插件不播放视频。还请大神，繁忙时间帮忙看一下～

**Comment by aliarmo** [comment]
那必须可以的，组件的json文件有引入视频插件吗

**Comment by 0wlism** [comment]
我也遇到这个问题，为啥放到自己的组件内就解析不了，放外面就行
