### ISSUE TITLE
能否支持 js api 的方式开启、关闭静音？

### ISSUE THREAD

**Issue by lilywang711** [tvfe/txv-miniprogram-plugin#88]
能否支持 js api 的方式开启、关闭静音？

**Comment by aliarmo** [comment]
通过一个state控制传入的muted属性即可，如：
`<txv-video 
 muted="{{muted}}"
  vid="e0354z3cqjp"   // 可使用vid="{{vid}}" wx:if="{{vid}}" 的方式应用data变量,要注意确保vid存在，详情可见文档最后面的tips
  playerid="txv1"     //playerid必须要全局唯一，可以设置为vid
  autoplay="{{true}}" // 是否自动播放
></txv-video>`
