### ISSUE TITLE
QQ小程序引用 报错  “没有对应的小程序版本”

### ISSUE THREAD

**Issue by heheLT** [tvfe/txv-miniprogram-plugin#91]
`"plugins": {
    "tencentvideo": {
      "version": "1.3.6",
      "provider": "wxa75efa648b60994b"
    }
  }`

**Comment by aliarmo** [comment]
请看readme，https://github.com/tvfe/txv-miniprogram-plugin
// 在app.json里面引入插件，注意插件版本号填最新的版本号
"plugins": {
  "tencentvideo": {
    "version": "1.0.0",        // QQ小程序插件版本号
    "provider": "1109840991"   // QQ小程序的APPID
  }
}
