### ISSUE TITLE
报错TypeError: Cannot read property 'elem' of undefined 怎么解决

### ISSUE THREAD

**Issue by timosss** [tvfe/txv-miniprogram-plugin#92]
![微信截图_20200218212422](https://user-images.githubusercontent.com/27383568/74740108-33bf4800-5295-11ea-9c27-d15d81f6a738.png)
另外怎么申请插件使用？申请入口在哪里？我填写座机的WXid就提示版本不存在
![微信图片_20200218212744](https://user-images.githubusercontent.com/27383568/74740277-8567d280-5295-11ea-9efa-fd48f55e2aaa.png)

**Comment by aliarmo** [comment]
1、这个是开发者工具问题，不用管，不影响
2、请看readme，https://github.com/tvfe/txv-miniprogram-plugin
