### ISSUE TITLE
Url "http://livep.l.qq.com/livemsg ... not in plugin's domain list

### ISSUE THREAD

**Issue by tywali** [tvfe/txv-miniprogram-plugin#96]
在微信开发工具中引入播放器插件，执行时报告如下错误：
VM1470:1 Url "http://livep.l.qq.com/livemsg?oid=225583000&cid=259006878&ping_data=EAAoAEAc_viewid_BKRS_r_W65xcbd9xNSgX0PSjZsKnK!JYSt2!MiIeKbs28vcTzvAzj!cs5P0Cr5A44xzMW2L!_RJBxDTuPLrtNdLERmxQ_pEimoRZix22b7h_oTP3OmH5BzEL5o!KkGRcRPPvTYqCd5RfVareaYqEOQ&adtype=WL&appversion=0&contract=2&i=1&os=2&datatype=jsonp&etype=1001&ch=100000004&seq=1&aseq=1&tailroll=1&xp=3&reporttime=0&t=0&url=&vid=n3065vvvcom&coverid=&pf=H5&vptag=&pid=&chid=41&tpid=60" not in plugin's domain list. This network request will be blocked in release version.

**Comment by chenguzhen87** [comment]
同问
