### ISSUE TITLE
tvpUrl 返回域名为「vhot2hls.tc.qq.com」的视频播放不了，返回403

### ISSUE THREAD

**Issue by qiuguorong** [tvfe/txv-miniprogram-plugin#98]
根据插件Log提示，返回的视频域名存在两种情况
1. 返回「IP」类型域名的视频源
2. 返回「vhot2hls.tc.qq.com」域名的视频源

「IP」类型域名可以正常播放，但是「vhot2hls.tc.qq.com」播放不了。请问在什么情况下会返回「vhot2hls.tc.qq.com」情况，该如何解决？

如以下两种域名的区别：
http://122.228.238.143/om.tc.qq.com/AeCFYC0xWwaqt9Ccpq0M5448hTfZHMzBOhYIVj_IHbb8/uwMROfz2r5zEIaQXGdGnC2dfDmafRkP9ujxgqKjuATzMrE-2/n09576avcwz.mp4?vkey=C597FB542250B33087BF57DD8F9E0279681C770FDF2A681A9E9DED82D60CECF949308964C839A384ED509D6FC68694A3EA6855C6F123C91F5B2236302BA5885C16E5095AF912F57578F5CF2F4F57F3BD2E9A1DF492CEF43D601F31AF39A40236D3AE7362989D9306541CD473B5BEA1B4&br=34&fmt=auto&level=0&platform=4210801&sdtfrom=v4169

http://vhot2hls.tc.qq.com/mp4/0/KdwF74VVv_7bodyoTAAw5gVEqLcrrDNdorqpoBTzpSWto0pwhXXuqQ/zX1of9nb3snBHk74v4R0dMlr_y4QYc4L5CB5JIHNrF2bISjGUXgDYU1_yp_sAS5cqYaN7a3BrlYiavjxidIPT_sixGezJzL6uzeWGSByG8QcPcBu-Sz8IAoLoal8op2qwbft36f5-bPvzMvWsMdzIw/n09576avcwz.mp4/n09576avcwz.mp4.av.m3u8?fn=mp4&bw=64&st=0&et=0&iv=&ivfn=&ivfc=&ivt=&ivs=&ivd=&ivl=&ftype=mp4&fbw=46&type=m3u8&drm=0&platform=4210801&sdtfrom=v4169

**Comment by dhkoma** [comment]
已经修复，原因是播放HLS格式却返回了MP4
