### ISSUE TITLE
QQ小程序使用该插件无法过审

### ISSUE THREAD

**Issue by dunkong** [tvfe/txv-miniprogram-plugin#99]
如题，使用该插件在QQ小程序中依旧需要提供文娱视频资质，请问这个后面会有改动吗？

**Comment by wangwenjie1314** [comment]
![image](https://user-images.githubusercontent.com/4018406/92440832-aebf6000-f1df-11ea-883c-5dddd70f2bfe.png)
https://mp.weixin.qq.com/wxopen/plugindevdoc?appid=wxa75efa648b60994b&token=&lang=zh_CN

**Comment by dunkong** [comment]
> ![image](https://user-images.githubusercontent.com/4018406/92440832-aebf6000-f1df-11ea-883c-5dddd70f2bfe.png)
> https://mp.weixin.qq.com/wxopen/plugindevdoc?appid=wxa75efa648b60994b&token=&lang=zh_CN

这些条件都是满足的，但是是在QQ小程序上面使用，QQ小程序的运营人员貌似不认这个插件

**Comment by wangwenjie1314** [comment]
考虑下后端解析抓取吧
微信小程序video组件调用腾讯视频的解决方案 https://jiezhe.net/post/38.html

**Comment by dunkong** [comment]
> 考虑下后端解析抓取吧
> 微信小程序video组件调用腾讯视频的解决方案 https://jiezhe.net/post/38.html

这些都不是问题，包括这个插件在QQ小程序上面使用也是正常的，但是QQ小程序的审核人员不会因为用了这个插件就不要文娱->视频资质了，无法过审

**Comment by ofshellohicy** [comment]
主要是审核人员不给过
